# Generated by Django 4.1.3 on 2022-11-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahs', '0003_alter_pageimage_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageimage',
            name='caption',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
