# Generated by Django 4.1.3 on 2022-11-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahs', '0004_alter_pageimage_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pageimage',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
