# Generated by Django 4.1.3 on 2022-12-05 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bahs', '0008_page_page_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageTags',
            new_name='PageTag',
        ),
    ]
