# Generated by Django 4.1.3 on 2022-12-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bahs', '0010_page_related_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='attribution',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
